blueprint:
  name: Mike Notify Humidity
  description: Notify if the humidity
  domain: automation
  input:
    window_sensor:
      name: Window Sensor
      description: Window open/closed sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
    humidity_difference:
      name: Luftfeuchtigkeit Unterschied
      description: Difference of the absolute humidity between the room and the outside
      selector:
        entity:
          filter:
            domain: sensor
    humidity_sensor:
      name: Luftfeuchtigkeit
      description: humidity of the room
      selector:
        entity:
          filter:
            domain: sensor
    open_action:
      name: Additional Open Action (Optional)
      description: Action to perform if the door/window sensor is opened (e.g. open
        blind, tts announcement)
      default: []
      selector:
        action: {}
    close_action:
      name: Additional Close Action (Optional)
      description: Action to perform if the door/window sensor is cloed again (e.g.
        close blind, tts announcement)
      default: []
      selector:
        action: {}

variables:
  open_action: !input open_action
  close_action: !input close_action

triggers:
  - trigger: numeric_state
    entity_id: !input humidity_difference
    above: 4.5
    id: above
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: numeric_state
    entity_id: !input humidity_sensor
    above: 60
    id: aboverel
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - trigger: numeric_state
    entity_id: !input humidity_difference
    below: 4
    id: below
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: numeric_state
    entity_id: !input humidity_sensor
    below: 56
    id: belowrel
    for:
      hours: 0
      minutes: 2
      seconds: 0

condition:
  - condition: or
    conditions:
      - condition: trigger
        id: below
      - condition: and
        conditions:
          - condition: trigger
            id: above
          - condition: numeric_state
            entity_id: !input humidity_sensor
            above: 55
      - condition: and
        conditions:
          - condition: trigger
            id: aboverel
          - condition: numeric_state
            entity_id: !input humidity_difference
            above: 3

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: above
              - condition: trigger
                id: aboverel
        sequence:
          - service: notify.notify
            data:
              title: Bitte Fenster öffnen
              message: >-
                Die Luftfeuchtigkeit in der Wohnung ist hoch im Vergleich zu
                außen. Bitte ein Fenster öffnen!
          - condition: time
            after: "08:00:00"
            before: "22:30:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
              - sun
          - choose:
              - conditions: '{{ open_action is defined and open_action | length > 0 }}'
                sequence: !input open_action
    default:
      - condition: state
        entity_id: !input window_sensor
        state: "on"
      - service: notify.notify
        data:
          title: Fenster kann wieder geschlossen werden.
          message: Die Luftfeuchtigkeit hat sich ausreichend angeglichen.
      - choose:
          - conditions: '{{ close_action is defined and close_action | length > 0 }}'
            sequence: !input close_action
mode: single
